const toolsData = [
    {
        id: 1,
        name: "ChatGPT",
        category: "writing",
        pricing: "freemium",
        description: "Advanced AI chatbot for conversations, writing assistance, coding help, and general knowledge queries.",
        website: "https://chat.openai.com",
        logo: "https://openai.com/favicon.ico",
        userCount: "100M+",
        rating: 4.8
    },
    {
        id: 2,
        name: "GitHub Copilot",
        category: "development",
        pricing: "paid",
        description: "AI-powered code completion and programming assistant that helps developers write code faster.",
        website: "https://github.com/features/copilot",
        logo: "https://github.githubassets.com/favicons/favicon.svg",
        userCount: "5M+",
        rating: 4.7
    },
    {
        id: 3,
        name: "Midjourney",
        category: "image",
        pricing: "paid",
        description: "AI art generator that creates stunning images from text descriptions with artistic styles.",
        website: "https://midjourney.com",
        logo: "https://cdn.discordapp.com/icons/662267976984297473/a_48f9159d64bcbc916bd8600fbab5d5b6.gif",
        userCount: "20M+",
        rating: 4.9
    },
    {
        id: 4,
        name: "Jasper AI",
        category: "writing",
        pricing: "paid",
        description: "AI writing assistant for marketing copy, blog posts, social media content, and business communications.",
        website: "https://jasper.ai",
        logo: "https://www.jasper.ai/favicon.ico",
        userCount: "1M+",
        rating: 4.6
    },
    {
        id: 5,
        name: "Synthesia",
        category: "video",
        pricing: "paid",
        description: "AI video generation platform that creates professional videos with AI avatars from text scripts.",
        website: "https://synthesia.io",
        logo: "https://synthesia.io/favicon.ico",
        userCount: "500K+",
        rating: 4.5
    },
    {
        id: 6,
        name: "Notion AI",
        category: "productivity",
        pricing: "freemium",
        description: "AI-powered features within Notion for writing, brainstorming, and content organization.",
        website: "https://notion.so/product/ai",
        logo: "https://notion.so/favicon.ico",
        userCount: "30M+",
        rating: 4.7
    },
    {
        id: 7,
        name: "Runway",
        category: "video",
        pricing: "freemium",
        description: "AI-powered creative tools for video editing, image generation, and visual effects.",
        website: "https://runwayml.com",
        logo: "https://runwayml.com/favicon.ico",
        userCount: "2M+",
        rating: 4.6
    },
    {
        id: 8,
        name: "InVideo",
        category: "video",
        pricing: "freemium",
        description: "AI video creation platform with templates, stock footage, and automated editing features.",
        website: "https://invideo.io",
        logo: "https://invideo.io/favicon.ico",
        userCount: "7M+",
        rating: 4.4
    },
    {
        id: 9,
        name: "HeyGen",
        category: "video",
        pricing: "paid",
        description: "AI avatar video generator that creates personalized spokesperson videos from text.",
        website: "https://heygen.com",
        logo: "https://heygen.com/favicon.ico",
        userCount: "1M+",
        rating: 4.5
    },
    {
        id: 10,
        name: "Pictory",
        category: "video",
        pricing: "paid",
        description: "AI-powered video creation from long-form content, perfect for social media and marketing.",
        website: "https://pictory.ai",
        logo: "https://pictory.ai/favicon.ico",
        userCount: "800K+",
        rating: 4.3
    },
    {
        id: 11,
        name: "Lumen5",
        category: "video",
        pricing: "freemium",
        description: "AI video maker that transforms text content into engaging video presentations automatically.",
        website: "https://lumen5.com",
        logo: "https://lumen5.com/favicon.ico",
        userCount: "10M+",
        rating: 4.4
    },
    {
        id: 12,
        name: "Sora",
        category: "video",
        pricing: "paid",
        description: "OpenAI's text-to-video model that generates realistic and imaginative video scenes from text prompts.",
        website: "https://openai.com/sora",
        logo: "https://openai.com/favicon.ico",
        userCount: "Limited Beta",
        rating: 4.8
    },
    {
        id: 13,
        name: "Claude",
        category: "chatbots",
        pricing: "freemium",
        description: "Anthropic's AI assistant focused on being helpful, harmless, and honest in conversations.",
        website: "https://claude.ai",
        logo: "https://claude.ai/favicon.ico",
        userCount: "5M+",
        rating: 4.7
    },
    {
        id: 14,
        name: "Perplexity AI",
        category: "research",
        pricing: "freemium",
        description: "AI-powered search engine that provides accurate answers with cited sources.",
        website: "https://perplexity.ai",
        logo: "https://perplexity.ai/favicon.ico",
        userCount: "10M+",
        rating: 4.6
    },
    {
        id: 15,
        name: "Grammarly",
        category: "writing",
        pricing: "freemium",
        description: "AI writing assistant that helps with grammar, spelling, tone, and style improvements.",
        website: "https://grammarly.com",
        logo: "https://grammarly.com/favicon.ico",
        userCount: "30M+",
        rating: 4.5
    },
    {
        id: 16,
        name: "Copy.ai",
        category: "writing",
        pricing: "freemium",
        description: "AI copywriting tool for marketing content, social media posts, and business communications.",
        website: "https://copy.ai",
        logo: "https://copy.ai/favicon.ico",
        userCount: "10M+",
        rating: 4.4
    },
    {
        id: 17,
        name: "Writesonic",
        category: "writing",
        pricing: "freemium",
        description: "AI writing platform for articles, ads, landing pages, and e-commerce product descriptions.",
        website: "https://writesonic.com",
        logo: "https://writesonic.com/favicon.ico",
        userCount: "5M+",
        rating: 4.3
    },
    {
        id: 18,
        name: "Rytr",
        category: "writing",
        pricing: "freemium",
        description: "AI writing assistant that generates high-quality content for blogs, emails, and social media.",
        website: "https://rytr.me",
        logo: "https://rytr.me/favicon.ico",
        userCount: "7M+",
        rating: 4.2
    },
    {
        id: 19,
        name: "Canva AI",
        category: "design",
        pricing: "freemium",
        description: "AI-powered design tools within Canva for creating graphics, presentations, and visual content.",
        website: "https://canva.com/ai-image-generator",
        logo: "https://canva.com/favicon.ico",
        userCount: "135M+",
        rating: 4.6
    },
    {
        id: 20,
        name: "DALL-E 3",
        category: "image",
        pricing: "paid",
        description: "OpenAI's advanced image generation model that creates detailed images from text descriptions.",
        website: "https://openai.com/dall-e-3",
        logo: "https://openai.com/favicon.ico",
        userCount: "10M+",
        rating: 4.7
    },
    {
        id: 21,
        name: "Stable Diffusion",
        category: "image",
        pricing: "free",
        description: "Open-source AI model for generating images from text, available through various platforms.",
        website: "https://stability.ai/stable-diffusion",
        logo: "https://stability.ai/favicon.ico",
        userCount: "50M+",
        rating: 4.5
    },
    {
        id: 22,
        name: "Adobe Firefly",
        category: "image",
        pricing: "freemium",
        description: "Adobe's AI art generator integrated into Creative Cloud apps for commercial-safe content creation.",
        website: "https://firefly.adobe.com",
        logo: "https://adobe.com/favicon.ico",
        userCount: "1B+",
        rating: 4.4
    },
    {
        id: 23,
        name: "Leonardo AI",
        category: "image",
        pricing: "freemium",
        description: "AI image generator focused on game assets, concept art, and creative illustrations.",
        website: "https://leonardo.ai",
        logo: "https://leonardo.ai/favicon.ico",
        userCount: "4M+",
        rating: 4.6
    },
    {
        id: 24,
        name: "Figma AI",
        category: "design",
        pricing: "freemium",
        description: "AI-powered design features in Figma for wireframing, prototyping, and design automation.",
        website: "https://figma.com/ai",
        logo: "https://figma.com/favicon.ico",
        userCount: "50M+",
        rating: 4.7
    },
    {
        id: 25,
        name: "Framer AI",
        category: "design",
        pricing: "paid",
        description: "AI website builder that creates responsive web designs from simple text descriptions.",
        website: "https://framer.com/ai",
        logo: "https://framer.com/favicon.ico",
        userCount: "1M+",
        rating: 4.5
    },
    {
        id: 26,
        name: "Looka",
        category: "design",
        pricing: "paid",
        description: "AI logo maker and brand kit generator for creating professional brand identities.",
        website: "https://looka.com",
        logo: "https://looka.com/favicon.ico",
        userCount: "10M+",
        rating: 4.3
    },
    {
        id: 27,
        name: "Brandmark",
        category: "design",
        pricing: "paid",
        description: "AI-powered logo design tool that creates unique brand marks and business card designs.",
        website: "https://brandmark.io",
        logo: "https://brandmark.io/favicon.ico",
        userCount: "2M+",
        rating: 4.2
    },
    {
        id: 28,
        name: "Remove.bg",
        category: "image",
        pricing: "freemium",
        description: "AI background removal tool that automatically cuts out image backgrounds in seconds.",
        website: "https://remove.bg",
        logo: "https://remove.bg/favicon.ico",
        userCount: "300M+",
        rating: 4.6
    },
    {
        id: 29,
        name: "Upscale.media",
        category: "image",
        pricing: "freemium",
        description: "AI image upscaler that enhances photo resolution and quality using machine learning.",
        website: "https://upscale.media",
        logo: "https://upscale.media/favicon.ico",
        userCount: "5M+",
        rating: 4.4
    },
    {
        id: 30,
        name: "Topaz Labs",
        category: "image",
        pricing: "paid",
        description: "AI-powered photo enhancement software for noise reduction, sharpening, and upscaling.",
        website: "https://topazlabs.com",
        logo: "https://topazlabs.com/favicon.ico",
        userCount: "1M+",
        rating: 4.7
    },
    {
        id: 31,
        name: "ElevenLabs",
        category: "audio",
        pricing: "freemium",
        description: "AI voice synthesis platform for creating realistic speech from text in multiple languages.",
        website: "https://elevenlabs.io",
        logo: "https://elevenlabs.io/favicon.ico",
        userCount: "1M+",
        rating: 4.8
    },
    {
        id: 32,
        name: "Murf AI",
        category: "audio",
        pricing: "paid",
        description: "AI voice generator for creating professional voiceovers and narrations from text.",
        website: "https://murf.ai",
        logo: "https://murf.ai/favicon.ico",
        userCount: "4M+",
        rating: 4.5
    },
    {
        id: 33,
        name: "Speechify",
        category: "audio",
        pricing: "freemium",
        description: "AI text-to-speech app that reads documents, articles, and PDFs aloud naturally.",
        website: "https://speechify.com",
        logo: "https://speechify.com/favicon.ico",
        userCount: "20M+",
        rating: 4.6
    },
    {
        id: 34,
        name: "Descript",
        category: "audio",
        pricing: "freemium",
        description: "AI-powered audio and video editing platform with transcription and voice cloning features.",
        website: "https://descript.com",
        logo: "https://descript.com/favicon.ico",
        userCount: "1M+",
        rating: 4.4
    },
    {
        id: 35,
        name: "AIVA",
        category: "audio",
        pricing: "freemium",
        description: "AI music composition assistant that creates original soundtracks and musical pieces.",
        website: "https://aiva.ai",
        logo: "https://aiva.ai/favicon.ico",
        userCount: "200K+",
        rating: 4.3
    },
    {
        id: 36,
        name: "Suno AI",
        category: "audio",
        pricing: "freemium",
        description: "AI music generator that creates complete songs with vocals from text prompts.",
        website: "https://suno.ai",
        logo: "https://suno.ai/favicon.ico",
        userCount: "10M+",
        rating: 4.7
    },
    {
        id: 37,
        name: "Udio",
        category: "audio",
        pricing: "freemium",
        description: "AI music creation platform for generating high-quality songs and instrumentals.",
        website: "https://udio.com",
        logo: "https://udio.com/favicon.ico",
        userCount: "2M+",
        rating: 4.5
    },
    {
        id: 38,
        name: "Zapier AI",
        category: "automation",
        pricing: "freemium",
        description: "AI-powered workflow automation that connects apps and automates repetitive tasks.",
        website: "https://zapier.com/ai",
        logo: "https://zapier.com/favicon.ico",
        userCount: "5M+",
        rating: 4.6
    },
    {
        id: 39,
        name: "Make (Integromat)",
        category: "automation",
        pricing: "freemium",
        description: "Visual automation platform with AI features for complex workflow integration.",
        website: "https://make.com",
        logo: "https://make.com/favicon.ico",
        userCount: "500K+",
        rating: 4.5
    },
    {
        id: 40,
        name: "UiPath",
        category: "automation",
        pricing: "paid",
        description: "Enterprise RPA platform with AI capabilities for business process automation.",
        website: "https://uipath.com",
        logo: "https://uipath.com/favicon.ico",
        userCount: "1M+",
        rating: 4.4
    },
    {
        id: 41,
        name: "Monday.com AI",
        category: "productivity",
        pricing: "paid",
        description: "AI-enhanced project management platform with automated insights and task optimization.",
        website: "https://monday.com/ai",
        logo: "https://monday.com/favicon.ico",
        userCount: "180K+",
        rating: 4.6
    },
    {
        id: 42,
        name: "Trello AI",
        category: "productivity",
        pricing: "freemium",
        description: "AI-powered features in Trello for automated project management and task organization.",
        website: "https://trello.com/ai",
        logo: "https://trello.com/favicon.ico",
        userCount: "50M+",
        rating: 4.3
    },
    {
        id: 43,
        name: "Asana AI",
        category: "productivity",
        pricing: "paid",
        description: "AI-driven project insights and automation features within Asana's work management platform.",
        website: "https://asana.com/ai",
        logo: "https://asana.com/favicon.ico",
        userCount: "100K+",
        rating: 4.5
    },
    {
        id: 44,
        name: "Calendly AI",
        category: "productivity",
        pricing: "freemium",
        description: "AI scheduling assistant that optimizes meeting times and automates appointment booking.",
        website: "https://calendly.com",
        logo: "https://calendly.com/favicon.ico",
        userCount: "20M+",
        rating: 4.7
    },
    {
        id: 45,
        name: "Otter.ai",
        category: "productivity",
        pricing: "freemium",
        description: "AI meeting assistant that transcribes, summarizes, and extracts action items from conversations.",
        website: "https://otter.ai",
        logo: "https://otter.ai/favicon.ico",
        userCount: "5M+",
        rating: 4.4
    },
    {
        id: 46,
        name: "HubSpot AI",
        category: "marketing",
        pricing: "freemium",
        description: "AI-powered marketing automation, content creation, and customer relationship management.",
        website: "https://hubspot.com/artificial-intelligence",
        logo: "https://hubspot.com/favicon.ico",
        userCount: "135K+",
        rating: 4.5
    },
    {
        id: 47,
        name: "Mailchimp AI",
        category: "marketing",
        pricing: "freemium",
        description: "AI email marketing features including content optimization and audience segmentation.",
        website: "https://mailchimp.com/features/ai-powered-tools",
        logo: "https://mailchimp.com/favicon.ico",
        userCount: "13M+",
        rating: 4.3
    },
    {
        id: 48,
        name: "Hootsuite AI",
        category: "marketing",
        pricing: "paid",
        description: "AI social media management with automated posting, content suggestions, and analytics.",
        website: "https://hootsuite.com/products/insights",
        logo: "https://hootsuite.com/favicon.ico",
        userCount: "18M+",
        rating: 4.2
    },
    {
        id: 49,
        name: "Buffer AI",
        category: "marketing",
        pricing: "freemium",
        description: "AI-enhanced social media scheduling with content optimization and performance insights.",
        website: "https://buffer.com/ai-assistant",
        logo: "https://buffer.com/favicon.ico",
        userCount: "75K+",
        rating: 4.4
    },
    {
        id: 50,
        name: "Surfer SEO",
        category: "marketing",
        pricing: "paid",
        description: "AI SEO tool for content optimization, keyword research, and SERP analysis.",
        website: "https://surferseo.com",
        logo: "https://surferseo.com/favicon.ico",
        userCount: "150K+",
        rating: 4.6
    },
    {
        id: 51,
        name: "MarketMuse",
        category: "marketing",
        pricing: "paid",
        description: "AI content planning and optimization platform for content marketing strategies.",
        website: "https://marketmuse.com",
        logo: "https://marketmuse.com/favicon.ico",
        userCount: "5K+",
        rating: 4.5
    },
    {
        id: 52,
        name: "Frase",
        category: "marketing",
        pricing: "paid",
        description: "AI content research and optimization tool for SEO-friendly article creation.",
        website: "https://frase.io",
        logo: "https://frase.io/favicon.ico",
        userCount: "30K+",
        rating: 4.4
    },
    {
        id: 53,
        name: "Clearscope",
        category: "marketing",
        pricing: "paid",
        description: "AI content optimization platform that helps create search-optimized content.",
        website: "https://clearscope.io",
        logo: "https://clearscope.io/favicon.ico",
        userCount: "3K+",
        rating: 4.7
    },
    {
        id: 54,
        name: "Consensus",
        category: "research",
        pricing: "freemium",
        description: "AI research assistant that finds and summarizes scientific papers and studies.",
        website: "https://consensus.app",
        logo: "https://consensus.app/favicon.ico",
        userCount: "1M+",
        rating: 4.6
    },
    {
        id: 55,
        name: "Semantic Scholar",
        category: "research",
        pricing: "free",
        description: "AI-powered academic search engine for finding relevant scientific literature.",
        website: "https://semanticscholar.org",
        logo: "https://semanticscholar.org/favicon.ico",
        userCount: "5M+",
        rating: 4.5
    },
    {
        id: 56,
        name: "Elicit",
        category: "research",
        pricing: "freemium",
        description: "AI research assistant that helps automate literature reviews and research workflows.",
        website: "https://elicit.org",
        logo: "https://elicit.org/favicon.ico",
        userCount: "200K+",
        rating: 4.4
    },
    {
        id: 57,
        name: "ResearchRabbit",
        category: "research",
        pricing: "free",
        description: "AI-powered research discovery platform for finding and organizing academic papers.",
        website: "https://researchrabbit.ai",
        logo: "https://researchrabbit.ai/favicon.ico",
        userCount: "100K+",
        rating: 4.3
    },
    {
        id: 58,
        name: "Scite",
        category: "research",
        pricing: "freemium",
        description: "AI platform that analyzes citation context to help evaluate research reliability.",
        website: "https://scite.ai",
        logo: "https://scite.ai/favicon.ico",
        userCount: "500K+",
        rating: 4.6
    },
    {
        id: 59,
        name: "Bard",
        category: "chatbots",
        pricing: "free",
        description: "Google's AI chatbot for conversations, creative tasks, and information retrieval.",
        website: "https://bard.google.com",
        logo: "https://google.com/favicon.ico",
        userCount: "100M+",
        rating: 4.5
    },
    {
        id: 60,
        name: "Bing Chat",
        category: "chatbots",
        pricing: "free",
        description: "Microsoft's AI-powered search chat experience integrated with Bing search results.",
        website: "https://bing.com/chat",
        logo: "https://bing.com/favicon.ico",
        userCount: "100M+",
        rating: 4.3
    },
    {
        id: 61,
        name: "Character.AI",
        category: "chatbots",
        pricing: "freemium",
        description: "AI platform for creating and chatting with AI characters and personalities.",
        website: "https://character.ai",
        logo: "https://character.ai/favicon.ico",
        userCount: "20M+",
        rating: 4.4
    },
    {
        id: 62,
        name: "Replika",
        category: "chatbots",
        pricing: "freemium",
        description: "AI companion chatbot designed for personal conversations and emotional support.",
        website: "https://replika.ai",
        logo: "https://replika.ai/favicon.ico",
        userCount: "10M+",
        rating: 4.2
    },
    {
        id: 63,
        name: "Poe",
        category: "chatbots",
        pricing: "freemium",
        description: "Quora's AI platform providing access to multiple AI models in one interface.",
        website: "https://poe.com",
        logo: "https://quora.com/favicon.ico",
        userCount: "5M+",
        rating: 4.5
    },
    {
        id: 64,
        name: "Google Analytics Intelligence",
        category: "analytics",
        pricing: "free",
        description: "AI insights and automated analysis features within Google Analytics platform.",
        website: "https://analytics.google.com/analytics/intelligence",
        logo: "https://google.com/favicon.ico",
        userCount: "37M+",
        rating: 4.4
    },
    {
        id: 65,
        name: "Mixpanel",
        category: "analytics",
        pricing: "freemium",
        description: "AI-powered product analytics for understanding user behavior and conversion optimization.",
        website: "https://mixpanel.com",
        logo: "https://mixpanel.com/favicon.ico",
        userCount: "26K+",
        rating: 4.5
    },
    {
        id: 66,
        name: "Amplitude",
        category: "analytics",
        pricing: "freemium",
        description: "AI digital analytics platform for product intelligence and user journey analysis.",
        website: "https://amplitude.com",
        logo: "https://amplitude.com/favicon.ico",
        userCount: "2K+",
        rating: 4.6
    },
    {
        id: 67,
        name: "Tableau AI",
        category: "analytics",
        pricing: "paid",
        description: "AI-powered data visualization and business intelligence with automated insights.",
        website: "https://tableau.com/products/tableau-ai",
        logo: "https://tableau.com/favicon.ico",
        userCount: "86K+",
        rating: 4.5
    },
    {
        id: 68,
        name: "Power BI AI",
        category: "analytics",
        pricing: "paid",
        description: "Microsoft's AI-enhanced business analytics platform with natural language queries.",
        website: "https://powerbi.microsoft.com/ai",
        logo: "https://microsoft.com/favicon.ico",
        userCount: "5M+",
        rating: 4.4
    },
    {
        id: 69,
        name: "MonkeyLearn",
        category: "analytics",
        pricing: "freemium",
        description: "AI text analysis platform for sentiment analysis, classification, and data extraction.",
        website: "https://monkeylearn.com",
        logo: "https://monkeylearn.com/favicon.ico",
        userCount: "5K+",
        rating: 4.3
    },
    {
        id: 70,
        name: "Lexica",
        category: "image",
        pricing: "freemium",
        description: "AI art search engine and Stable Diffusion image generator with curated prompts.",
        website: "https://lexica.art",
        logo: "https://lexica.art/favicon.ico",
        userCount: "5M+",
        rating: 4.4
    },
    {
        id: 71,
        name: "Artbreeder",
        category: "image",
        pricing: "freemium",
        description: "AI image mixing platform for creating and evolving portraits, landscapes, and artworks.",
        website: "https://artbreeder.com",
        logo: "https://artbreeder.com/favicon.ico",
        userCount: "10M+",
        rating: 4.2
    },
    {
        id: 72,
        name: "NightCafe",
        category: "image",
        pricing: "freemium",
        description: "AI art generator with multiple algorithms for creating digital artwork from text.",
        website: "https://nightcafe.studio",
        logo: "https://nightcafe.studio/favicon.ico",
        userCount: "5M+",
        rating: 4.3
    },
    {
        id: 73,
        name: "Dream Studio",
        category: "image",
        pricing: "paid",
        description: "Stability AI's official interface for Stable Diffusion image generation.",
        website: "https://dreamstudio.ai",
        logo: "https://dreamstudio.ai/favicon.ico",
        userCount: "2M+",
        rating: 4.5
    },
    {
        id: 74,
        name: "Playground AI",
        category: "image",
        pricing: "freemium",
        description: "AI image generator with fine-tuned models for creating art, logos, and designs.",
        website: "https://playgroundai.com",
        logo: "https://playgroundai.com/favicon.ico",
        userCount: "1M+",
        rating: 4.4
    },
    {
        id: 75,
        name: "DeepL",
        category: "productivity",
        pricing: "freemium",
        description: "AI-powered translation service offering highly accurate translations across 30+ languages.",
        website: "https://deepl.com",
        logo: "https://deepl.com/favicon.ico",
        userCount: "1B+",
        rating: 4.8
    },
    {
        id: 76,
        name: "Replit AI",
        category: "development",
        pricing: "freemium",
        description: "AI coding assistant integrated into Replit's online development environment.",
        website: "https://replit.com/ai",
        logo: "https://replit.com/favicon.ico",
        userCount: "20M+",
        rating: 4.5
    },
    {
        id: 77,
        name: "Tabnine",
        category: "development",
        pricing: "freemium",
        description: "AI code completion assistant that integrates with popular IDEs and editors.",
        website: "https://tabnine.com",
        logo: "https://tabnine.com/favicon.ico",
        userCount: "1M+",
        rating: 4.3
    },
    {
        id: 78,
        name: "Codeium",
        category: "development",
        pricing: "freemium",
        description: "Free AI code completion and chat assistant for developers across multiple languages.",
        website: "https://codeium.com",
        logo: "https://codeium.com/favicon.ico",
        userCount: "500K+",
        rating: 4.6
    },
    {
        id: 79,
        name: "CodeWhisperer",
        category: "development",
        pricing: "freemium",
        description: "Amazon's AI coding companion that provides code suggestions and security scanning.",
        website: "https://aws.amazon.com/codewhisperer",
        logo: "https://aws.amazon.com/favicon.ico",
        userCount: "1M+",
        rating: 4.4
    },
    {
        id: 80,
        name: "Cursor",
        category: "development",
        pricing: "freemium",
        description: "AI-powered code editor built for pair programming with AI assistants.",
        website: "https://cursor.sh",
        logo: "https://cursor.sh/favicon.ico",
        userCount: "100K+",
        rating: 4.7
    },
    {
        id: 81,
        name: "Gamma",
        category: "productivity",
        pricing: "freemium",
        description: "AI presentation maker that creates beautiful slides, documents, and web pages from text.",
        website: "https://gamma.app",
        logo: "https://gamma.app/favicon.ico",
        userCount: "1M+",
        rating: 4.5
    },
    {
        id: 82,
        name: "Beautiful.AI",
        category: "productivity",
        pricing: "freemium",
        description: "AI-powered presentation software with smart design suggestions and templates.",
        website: "https://beautiful.ai",
        logo: "https://beautiful.ai/favicon.ico",
        userCount: "500K+",
        rating: 4.3
    },
    {
        id: 83,
        name: "Tome",
        category: "productivity",
        pricing: "freemium",
        description: "AI storytelling platform for creating presentations, outlines, and narratives.",
        website: "https://tome.app",
        logo: "https://tome.app/favicon.ico",
        userCount: "2M+",
        rating: 4.4
    },
    {
        id: 84,
        name: "Krisp",
        category: "audio",
        pricing: "freemium",
        description: "AI noise cancellation software for crystal-clear audio in calls and recordings.",
        website: "https://krisp.ai",
        logo: "https://krisp.ai/favicon.ico",
        userCount: "3M+",
        rating: 4.6
    },
    {
        id: 85,
        name: "Soundraw",
        category: "audio",
        pricing: "paid",
        description: "AI music generator for creating royalty-free background music for videos and projects.",
        website: "https://soundraw.io",
        logo: "https://soundraw.io/favicon.ico",
        userCount: "500K+",
        rating: 4.4
    },
    {
        id: 86,
        name: "Boomy",
        category: "audio",
        pricing: "freemium",
        description: "AI music creation platform that lets anyone make original songs instantly.",
        website: "https://boomy.com",
        logo: "https://boomy.com/favicon.ico",
        userCount: "3M+",
        rating: 4.2
    },
    {
        id: 87,
        name: "Beatoven.ai",
        category: "audio",
        pricing: "freemium",
        description: "AI music composer that creates mood-based background music for videos and podcasts.",
        website: "https://beatoven.ai",
        logo: "https://beatoven.ai/favicon.ico",
        userCount: "100K+",
        rating: 4.3
    },
    {
        id: 88,
        name: "Luma AI",
        category: "video",
        pricing: "freemium",
        description: "AI-powered 3D capture and realistic video generation from text prompts.",
        website: "https://lumalabs.ai",
        logo: "https://lumalabs.ai/favicon.ico",
        userCount: "1M+",
        rating: 4.6
    },
    {
        id: 89,
        name: "Pika Labs",
        category: "video",
        pricing: "freemium",
        description: "AI video generator that creates and edits videos from text descriptions.",
        website: "https://pika.art",
        logo: "https://pika.art/favicon.ico",
        userCount: "5M+",
        rating: 4.5
    },
    {
        id: 90,
        name: "Kapwing AI",
        category: "video",
        pricing: "freemium",
        description: "AI video editing tools including subtitle generation, background removal, and effects.",
        website: "https://kapwing.com/ai",
        logo: "https://kapwing.com/favicon.ico",
        userCount: "10M+",
        rating: 4.4
    },
    {
        id: 91,
        name: "Fliki",
        category: "video",
        pricing: "freemium",
        description: "AI video generator that creates videos from text using AI voices and stock footage.",
        website: "https://fliki.ai",
        logo: "https://fliki.ai/favicon.ico",
        userCount: "1M+",
        rating: 4.3
    },
    {
        id: 92,
        name: "Steve AI",
        category: "video",
        pricing: "paid",
        description: "AI video maker for creating animated and live-action videos from scripts.",
        website: "https://steve.ai",
        logo: "https://steve.ai/favicon.ico",
        userCount: "200K+",
        rating: 4.2
    },
    {
        id: 93,
        name: "Designs.ai",
        category: "design",
        pricing: "paid",
        description: "AI design suite with logo maker, video creator, speech maker, and design maker tools.",
        website: "https://designs.ai",
        logo: "https://designs.ai/favicon.ico",
        userCount: "5M+",
        rating: 4.3
    },
    {
        id: 94,
        name: "Uizard",
        category: "design",
        pricing: "freemium",
        description: "AI UI/UX design tool that transforms sketches and screenshots into digital designs.",
        website: "https://uizard.io",
        logo: "https://uizard.io/favicon.ico",
        userCount: "750K+",
        rating: 4.4
    },
    {
        id: 95,
        name: "Galileo AI",
        category: "design",
        pricing: "paid",
        description: "AI-powered UI design tool that generates high-fidelity designs from text descriptions.",
        website: "https://usegalileo.ai",
        logo: "https://usegalileo.ai/favicon.ico",
        userCount: "50K+",
        rating: 4.5
    },
    {
        id: 96,
        name: "Khroma",
        category: "design",
        pricing: "free",
        description: "AI color tool that learns your preferences and generates infinite color palettes.",
        website: "https://khroma.co",
        logo: "https://khroma.co/favicon.ico",
        userCount: "1M+",
        rating: 4.6
    },
    {
        id: 97,
        name: "Fronty",
        category: "development",
        pricing: "paid",
        description: "AI that converts image designs to HTML/CSS code automatically.",
        website: "https://fronty.com",
        logo: "https://fronty.com/favicon.ico",
        userCount: "100K+",
        rating: 4.2
    },
    {
        id: 98,
        name: "Sketch2Code",
        category: "development",
        pricing: "free",
        description: "Microsoft AI service that transforms hand-drawn UI sketches into working HTML code.",
        website: "https://sketch2code.azurewebsites.net",
        logo: "https://microsoft.com/favicon.ico",
        userCount: "500K+",
        rating: 4.1
    },
    {
        id: 99,
        name: "Wix ADI",
        category: "development",
        pricing: "freemium",
        description: "AI website builder that creates personalized websites based on user preferences.",
        website: "https://wix.com/website/adi",
        logo: "https://wix.com/favicon.ico",
        userCount: "200M+",
        rating: 4.3
    },
    {
        id: 100,
        name: "10Web AI",
        category: "development",
        pricing: "paid",
        description: "AI website builder and WordPress platform with automated optimization features.",
        website: "https://10web.io",
        logo: "https://10web.io/favicon.ico",
        userCount: "1M+",
        rating: 4.4
    },
    {
        id: 101,
        name: "Durable AI",
        category: "development",
        pricing: "paid",
        description: "AI website builder that creates complete business websites in 30 seconds.",
        website: "https://durable.co",
        logo: "https://durable.co/favicon.ico",
        userCount: "500K+",
        rating: 4.2
    },
    {
        id: 102,
        name: "Hostinger AI",
        category: "development",
        pricing: "paid",
        description: "AI website builder with hosting, offering quick site creation with AI assistance.",
        website: "https://hostinger.com/ai-website-builder",
        logo: "https://hostinger.com/favicon.ico",
        userCount: "2M+",
        rating: 4.3
    },
    {
        id: 103,
        name: "Tldraw",
        category: "design",
        pricing: "free",
        description: "AI-powered collaborative whiteboard with smart shape recognition and drawing assistance.",
        website: "https://tldraw.com",
        logo: "https://tldraw.com/favicon.ico",
        userCount: "1M+",
        rating: 4.5
    },
    {
        id: 104,
        name: "Excalidraw",
        category: "design",
        pricing: "free",
        description: "AI-enhanced virtual whiteboard for sketching hand-drawn like diagrams.",
        website: "https://excalidraw.com",
        logo: "https://excalidraw.com/favicon.ico",
        userCount: "5M+",
        rating: 4.6
    },
    {
        id: 105,
        name: "BestUtils Calculator",
        category: "productivity",
        pricing: "free",
        description: "Comprehensive online calculator platform with 200+ specialized calculators for finance, health, math, and more.",
        website: "https://bestutils.com",
        logo: "https://bestutils.com/favicon.ico",
        userCount: "5M+",
        rating: 4.8
    },
    {
        id: 106,
        name: "Humata AI",
        category: "research",
        pricing: "freemium",
        description: "AI research assistant that analyzes and answers questions about uploaded documents and PDFs.",
        website: "https://humata.ai",
        logo: "https://humata.ai/favicon.ico",
        userCount: "500K+",
        rating: 4.5
    },
    {
        id: 107,
        name: "ChatPDF",
        category: "research",
        pricing: "freemium",
        description: "AI tool that allows you to chat with PDF documents for quick information extraction.",
        website: "https://chatpdf.com",
        logo: "https://chatpdf.com/favicon.ico",
        userCount: "10M+",
        rating: 4.4
    },
    {
        id: 108,
        name: "PDF.ai",
        category: "research",
        pricing: "freemium",
        description: "AI-powered PDF analysis tool for document summarization and Q&A interactions.",
        website: "https://pdf.ai",
        logo: "https://pdf.ai/favicon.ico",
        userCount: "2M+",
        rating: 4.3
    },
    {
        id: 109,
        name: "Mem.ai",
        category: "productivity",
        pricing: "freemium",
        description: "AI note-taking app that automatically organizes and connects your thoughts and ideas.",
        website: "https://mem.ai",
        logo: "https://mem.ai/favicon.ico",
        userCount: "100K+",
        rating: 4.2
    },
    {
        id: 110,
        name: "Obsidian AI",
        category: "productivity",
        pricing: "freemium",
        description: "AI-enhanced knowledge management system with smart linking and content generation.",
        website: "https://obsidian.md",
        logo: "https://obsidian.md/favicon.ico",
        userCount: "1M+",
        rating: 4.7
    }
];